// Comprehensive seed data for Ele Cafe
// This file contains sample tea products organized by categories

// Serving options available for teas
export const servingOptions = {
  infused_tea: {
    id: 'infused_tea',
    name: 'Infused Tea',
    description: 'Traditional hot tea preparation with pure tea leaves',
    icon: '🍵',
    temperature: 'Hot',
    preparation_time: '3-5 minutes'
  },
  iced_tea: {
    id: 'iced_tea',
    name: 'Iced Tea',
    description: 'Refreshing cold-brewed tea served over ice',
    icon: '🧊',
    temperature: 'Cold',
    preparation_time: '5-7 minutes'
  },
  fresh_milk_iced_tea: {
    id: 'fresh_milk_iced_tea',
    name: 'Fresh Milk Iced Tea',
    description: 'Creamy iced tea blended with fresh milk',
    icon: '🥛',
    temperature: 'Cold',
    preparation_time: '6-8 minutes'
  },
  hot_tea_latte: {
    id: 'hot_tea_latte',
    name: 'Hot Tea Latte',
    description: 'Rich tea combined with steamed milk and foam',
    icon: '☕',
    temperature: 'Hot',
    preparation_time: '4-6 minutes'
  },
  bubble_tea: {
    id: 'bubble_tea',
    name: 'Bubble Tea',
    description: 'Fun tea drink with chewy tapioca pearls',
    icon: '🧋',
    temperature: 'Cold/Hot',
    preparation_time: '8-10 minutes'
  }
}

export const sampleTeaProducts = [
  // BLACK TEA CATEGORY
  {
    id: 'black-earl-grey',
    name: 'Earl Grey Supreme',
    category: 'Black Tea',
    type: 'tea_latte',
    price: 24.99,
    description: 'A classic Earl Grey blend with bergamot oil, cornflower petals, and a hint of vanilla. Perfect for afternoon tea.',
    ingredients: ['Black tea', 'Bergamot oil', 'Cornflower petals', 'Natural vanilla flavoring'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 3-5 minutes',
    caffeine_level: 'High',
    antioxidants: 'High',
    benefits: ['Boosts immunity', 'Supports heart health', 'Reduces inflammation', 'Aids digestion'],
    origin: 'Sri Lanka',
    regions: ['Nuwara Eliya', 'Dimbula', 'Uva'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 50,
    discount_active: true,
    discount_percentage: 15,
    seasonal_promotion: false,
    tags: ['classic', 'bergamot', 'afternoon'],
    image: '/images/earl-grey.jpg',
    rating: 4.8,
    reviews_count: 127,
    // Serving options available for this tea
    available_serving_options: ['infused_tea', 'iced_tea', 'hot_tea_latte', 'fresh_milk_iced_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'black-assam',
    name: 'Assam Gold',
    category: 'Black Tea',
    type: 'milk_tea',
    price: 22.99,
    description: 'Rich and malty Assam black tea with a robust flavor. Excellent with milk and sugar.',
    ingredients: ['Assam black tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 4-6 minutes',
    caffeine_level: 'High',
    antioxidants: 'Medium',
    benefits: ['Energy boost', 'Mental alertness', 'Heart health', 'Digestive support'],
    origin: 'Assam, India',
    regions: ['Upper Assam', 'Lower Assam'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 35,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['robust', 'malty', 'breakfast'],
    image: '/images/assam-gold.jpg',
    rating: 4.6,
    reviews_count: 89,
    available_serving_options: ['infused_tea', 'hot_tea_latte', 'fresh_milk_iced_tea'],
    default_serving_option: 'hot_tea_latte'
  },
  {
    id: 'black-english-breakfast',
    name: 'English Breakfast Blend',
    category: 'Black Tea',
    type: 'milk_tea',
    price: 21.99,
    description: 'Traditional English breakfast blend of Ceylon, Assam, and Kenyan black teas.',
    ingredients: ['Ceylon black tea', 'Assam black tea', 'Kenyan black tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 3-5 minutes',
    caffeine_level: 'High',
    antioxidants: 'High',
    benefits: ['Morning energy', 'Mental focus', 'Antioxidant boost', 'Traditional comfort'],
    origin: 'Blend',
    regions: ['Ceylon', 'Assam', 'Kenya'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 42,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: true,
    tags: ['breakfast', 'traditional', 'blend'],
    image: '/images/english-breakfast.jpg',
    rating: 4.7,
    reviews_count: 156,
    available_serving_options: ['infused_tea', 'hot_tea_latte', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'black-darjeeling',
    name: 'Darjeeling First Flush',
    category: 'Black Tea',
    type: 'infused_tea',
    price: 32.99,
    description: 'Delicate and floral first flush Darjeeling with muscatel notes. The champagne of teas.',
    ingredients: ['Darjeeling black tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 185°F water for 3-4 minutes',
    caffeine_level: 'Medium-High',
    antioxidants: 'Very High',
    benefits: ['Premium antioxidants', 'Delicate flavor', 'Mental clarity', 'Afternoon relaxation'],
    origin: 'Darjeeling, India',
    regions: ['Darjeeling Hills', 'West Bengal'],
    weight: '50g',
    in_stock: true,
    stock_quantity: 25,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['premium', 'floral', 'muscatel'],
    image: '/images/darjeeling.jpg',
    rating: 4.9,
    reviews_count: 73,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },

  // GREEN TEA CATEGORY
  {
    id: 'green-dragon-well',
    name: 'Dragon Well (Longjing)',
    category: 'Green Tea',
    type: 'infused_tea',
    price: 28.99,
    description: 'Premium Chinese green tea with a delicate, sweet flavor and beautiful flat leaves.',
    ingredients: ['Dragon Well green tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 2-3 minutes',
    caffeine_level: 'Medium',
    antioxidants: 'Very High',
    benefits: ['High antioxidants', 'Weight management', 'Brain health', 'Metabolism boost'],
    origin: 'Hangzhou, China',
    regions: ['West Lake', 'Hangzhou'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 30,
    discount_active: true,
    discount_percentage: 10,
    seasonal_promotion: false,
    tags: ['premium', 'delicate', 'chinese'],
    image: '/images/dragon-well.jpg',
    rating: 4.8,
    reviews_count: 94,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'green-genmaicha',
    name: 'Genmaicha (Popcorn Tea)',
    category: 'Green Tea',
    type: 'infused_tea',
    price: 19.99,
    description: 'Japanese green tea blended with roasted rice, creating a nutty and comforting flavor.',
    ingredients: ['Sencha green tea', 'Roasted rice'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 2-3 minutes',
    caffeine_level: 'Low-Medium',
    antioxidants: 'High',
    benefits: ['Digestive comfort', 'Low caffeine', 'Nutty flavor', 'Evening relaxation'],
    origin: 'Japan',
    regions: ['Shizuoka', 'Kagoshima'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 45,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: true,
    tags: ['nutty', 'comforting', 'japanese'],
    image: '/images/genmaicha.jpg',
    rating: 4.5,
    reviews_count: 112,
    available_serving_options: ['infused_tea', 'iced_tea', 'hot_tea_latte'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'green-matcha',
    name: 'Ceremonial Grade Matcha',
    category: 'Green Tea',
    type: 'tea_latte',
    price: 45.99,
    description: 'Premium ceremonial grade matcha powder from Uji, Japan. Perfect for traditional tea ceremony or lattes.',
    ingredients: ['Stone-ground matcha powder'],
    brewing_instructions: 'Whisk 1-2 tsp with 2oz of 175°F water until frothy',
    caffeine_level: 'High',
    antioxidants: 'Extremely High',
    benefits: ['Maximum antioxidants', 'Sustained energy', 'Mental focus', 'Ceremonial quality'],
    origin: 'Uji, Japan',
    regions: ['Uji', 'Kyoto'],
    weight: '30g',
    in_stock: true,
    stock_quantity: 20,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['ceremonial', 'premium', 'matcha'],
    image: '/images/matcha.jpg',
    rating: 4.9,
    reviews_count: 68,
    available_serving_options: ['infused_tea', 'hot_tea_latte', 'iced_tea', 'bubble_tea'],
    default_serving_option: 'hot_tea_latte'
  },
  {
    id: 'green-sencha',
    name: 'Sencha Supreme',
    category: 'Green Tea',
    type: 'infused_tea',
    price: 24.99,
    description: 'High-quality Japanese sencha with a fresh, grassy flavor and vibrant green color.',
    ingredients: ['Sencha green tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 1-2 minutes',
    caffeine_level: 'Medium',
    antioxidants: 'Very High',
    benefits: ['Fresh antioxidants', 'Natural energy', 'Immune support', 'Daily wellness'],
    origin: 'Shizuoka, Japan',
    regions: ['Shizuoka', 'Mount Fuji area'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 38,
    discount_active: true,
    discount_percentage: 20,
    seasonal_promotion: false,
    tags: ['fresh', 'grassy', 'japanese'],
    image: '/images/sencha.jpg',
    rating: 4.7,
    reviews_count: 145,
    available_serving_options: ['infused_tea', 'iced_tea', 'bubble_tea'],
    default_serving_option: 'infused_tea'
  },

  // WHITE TEA CATEGORY
  {
    id: 'white-silver-needle',
    name: 'Silver Needle (Bai Hao Yin Zhen)',
    category: 'White Tea',
    type: 'infused_tea',
    price: 55.99,
    description: 'The most prized white tea with delicate silver buds and a subtle, sweet flavor.',
    ingredients: ['White tea buds'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 4-6 minutes',
    caffeine_level: 'Low',
    antioxidants: 'Extremely High',
    benefits: ['Premium antioxidants', 'Anti-aging', 'Gentle energy', 'Skin health'],
    origin: 'Fujian, China',
    regions: ['Fujian Province', 'Fuding'],
    weight: '50g',
    in_stock: true,
    stock_quantity: 15,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['premium', 'delicate', 'rare'],
    image: '/images/silver-needle.jpg',
    rating: 4.9,
    reviews_count: 42,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'white-peony',
    name: 'White Peony (Bai Mu Dan)',
    category: 'White Tea',
    type: 'infused_tea',
    price: 34.99,
    description: 'Elegant white tea with a fuller body than Silver Needle, offering floral and fruity notes.',
    ingredients: ['White tea leaves and buds'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 3-5 minutes',
    caffeine_level: 'Low',
    antioxidants: 'Very High',
    benefits: ['Floral antioxidants', 'Gentle caffeine', 'Relaxation', 'Evening comfort'],
    origin: 'Fujian, China',
    regions: ['Fujian Province', 'Zhenghe'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 22,
    discount_active: true,
    discount_percentage: 12,
    seasonal_promotion: false,
    tags: ['elegant', 'floral', 'fruity'],
    image: '/images/white-peony.jpg',
    rating: 4.6,
    reviews_count: 67,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },

  // OOLONG TEA CATEGORY
  {
    id: 'oolong-tie-guan-yin',
    name: 'Tie Guan Yin (Iron Goddess)',
    category: 'Oolong Tea',
    type: 'infused_tea',
    price: 38.99,
    description: 'Classic Chinese oolong with a complex flavor profile ranging from floral to fruity.',
    ingredients: ['Tie Guan Yin oolong tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 195°F water for 3-4 minutes',
    caffeine_level: 'Medium',
    antioxidants: 'High',
    benefits: ['Complex antioxidants', 'Metabolism support', 'Mental clarity', 'Traditional wellness'],
    origin: 'Fujian, China',
    regions: ['Anxi County', 'Fujian'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 28,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: true,
    tags: ['complex', 'floral', 'traditional'],
    image: '/images/tie-guan-yin.jpg',
    rating: 4.8,
    reviews_count: 85,
    available_serving_options: ['infused_tea', 'iced_tea', 'bubble_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'oolong-da-hong-pao',
    name: 'Da Hong Pao (Big Red Robe)',
    category: 'Oolong Tea',
    type: 'infused_tea',
    price: 42.99,
    description: 'Legendary rock oolong from Wuyi Mountains with a rich, roasted flavor and mineral notes.',
    ingredients: ['Da Hong Pao oolong tea'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 200°F water for 3-5 minutes',
    caffeine_level: 'Medium-High',
    antioxidants: 'High',
    benefits: ['Legendary quality', 'Rich minerals', 'Deep flavor', 'Cultural heritage'],
    origin: 'Wuyi Mountains, China',
    regions: ['Wuyi Mountains', 'Fujian'],
    weight: '50g',
    in_stock: true,
    stock_quantity: 18,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['legendary', 'roasted', 'mineral'],
    image: '/images/da-hong-pao.jpg',
    rating: 4.9,
    reviews_count: 56,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },

  // HERBAL TEA CATEGORY
  {
    id: 'herbal-chamomile',
    name: 'Chamomile Dreams',
    category: 'Herbal Tea',
    type: 'infused_tea',
    price: 18.99,
    description: 'Soothing chamomile flowers perfect for relaxation and bedtime. Naturally caffeine-free.',
    ingredients: ['Chamomile flowers'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 5-7 minutes',
    caffeine_level: 'Caffeine-Free',
    antioxidants: 'Medium',
    benefits: ['Sleep support', 'Relaxation', 'Digestive comfort', 'Stress relief'],
    origin: 'Egypt',
    regions: ['Nile Delta', 'Fayoum'],
    weight: '50g',
    in_stock: true,
    stock_quantity: 55,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['soothing', 'bedtime', 'caffeine-free'],
    image: '/images/chamomile.jpg',
    rating: 4.5,
    reviews_count: 203,
    available_serving_options: ['infused_tea', 'iced_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'herbal-peppermint',
    name: 'Fresh Peppermint',
    category: 'Herbal Tea',
    type: 'iced_tea',
    price: 16.99,
    description: 'Refreshing peppermint leaves with a cool, invigorating flavor. Great hot or iced.',
    ingredients: ['Peppermint leaves'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 5-7 minutes',
    caffeine_level: 'Caffeine-Free',
    antioxidants: 'Medium',
    benefits: ['Digestive support', 'Refreshing', 'Cooling effect', 'Natural mint'],
    origin: 'Pacific Northwest',
    regions: ['Oregon', 'Washington'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 48,
    discount_active: true,
    discount_percentage: 25,
    seasonal_promotion: true,
    tags: ['refreshing', 'cooling', 'digestive'],
    image: '/images/peppermint.jpg',
    rating: 4.4,
    reviews_count: 178,
    available_serving_options: ['infused_tea', 'iced_tea', 'fresh_milk_iced_tea'],
    default_serving_option: 'iced_tea'
  },
  {
    id: 'herbal-rooibos',
    name: 'Red Bush Rooibos',
    category: 'Herbal Tea',
    type: 'milk_tea',
    price: 20.99,
    description: 'South African red bush tea with a naturally sweet, vanilla-like flavor. Caffeine-free.',
    ingredients: ['Rooibos'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 5-7 minutes',
    caffeine_level: 'Caffeine-Free',
    antioxidants: 'High',
    benefits: ['Natural sweetness', 'Caffeine-free', 'Mineral rich', 'Family friendly'],
    origin: 'South Africa',
    regions: ['Cederberg Mountains', 'Western Cape'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 33,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['sweet', 'vanilla', 'caffeine-free'],
    image: '/images/rooibos.jpg',
    rating: 4.6,
    reviews_count: 134,
    available_serving_options: ['infused_tea', 'hot_tea_latte', 'iced_tea', 'fresh_milk_iced_tea'],
    default_serving_option: 'hot_tea_latte'
  },

  // PU-ERH TEA CATEGORY
  {
    id: 'puerh-sheng',
    name: 'Raw Pu-erh (Sheng)',
    category: 'Pu-erh Tea',
    type: 'infused_tea',
    price: 48.99,
    description: 'Aged raw pu-erh with complex earthy flavors that develop over time. A true connoisseur\'s tea.',
    ingredients: ['Raw pu-erh tea'],
    brewing_instructions: 'Rinse leaves, then steep 1 tsp in 8oz of 200°F water for 30 seconds, increasing time with each steeping',
    caffeine_level: 'Medium',
    antioxidants: 'High',
    benefits: ['Aged complexity', 'Digestive support', 'Traditional fermentation', 'Connoisseur quality'],
    origin: 'Yunnan, China',
    regions: ['Yunnan Province', 'Pu-erh City'],
    weight: '357g (cake)',
    in_stock: true,
    stock_quantity: 12,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: false,
    tags: ['aged', 'earthy', 'complex'],
    image: '/images/raw-puerh.jpg',
    rating: 4.7,
    reviews_count: 39,
    available_serving_options: ['infused_tea'],
    default_serving_option: 'infused_tea'
  },

  // FLAVORED TEA CATEGORY
  {
    id: 'flavored-jasmine-green',
    name: 'Jasmine Phoenix Pearls',
    category: 'Flavored Tea',
    type: 'infused_tea',
    price: 35.99,
    description: 'Hand-rolled green tea pearls scented with fresh jasmine flowers. Aromatic and elegant.',
    ingredients: ['Green tea', 'Jasmine flowers'],
    brewing_instructions: 'Steep 1 tsp in 8oz of 175°F water for 2-3 minutes',
    caffeine_level: 'Medium',
    antioxidants: 'High',
    benefits: ['Floral aromatherapy', 'Green tea antioxidants', 'Elegant experience', 'Stress relief'],
    origin: 'Fujian, China',
    regions: ['Fujian Province', 'Fuzhou'],
    weight: '75g',
    in_stock: true,
    stock_quantity: 26,
    discount_active: true,
    discount_percentage: 18,
    seasonal_promotion: false,
    tags: ['aromatic', 'elegant', 'scented'],
    image: '/images/jasmine-pearls.jpg',
    rating: 4.8,
    reviews_count: 91,
    available_serving_options: ['infused_tea', 'iced_tea', 'bubble_tea'],
    default_serving_option: 'infused_tea'
  },
  {
    id: 'flavored-vanilla-chai',
    name: 'Vanilla Spice Chai',
    category: 'Flavored Tea',
    type: 'milk_tea',
    price: 23.99,
    description: 'Traditional Indian chai spices blended with black tea and natural vanilla. Perfect with milk.',
    ingredients: ['Black tea', 'Cinnamon', 'Cardamom', 'Ginger', 'Cloves', 'Black pepper', 'Natural vanilla'],
    brewing_instructions: 'Steep 1 tsp in 8oz of boiling water for 4-5 minutes, add milk and sweetener to taste',
    caffeine_level: 'High',
    antioxidants: 'Medium',
    benefits: ['Warming spices', 'Digestive support', 'Traditional comfort', 'Energy boost'],
    origin: 'India',
    regions: ['Assam', 'Kerala', 'Tamil Nadu'],
    weight: '100g',
    in_stock: true,
    stock_quantity: 41,
    discount_active: false,
    discount_percentage: 0,
    seasonal_promotion: true,
    tags: ['spiced', 'warming', 'traditional'],
    image: '/images/vanilla-chai.jpg',
    rating: 4.7,
    reviews_count: 167,
    available_serving_options: ['infused_tea', 'hot_tea_latte', 'iced_tea', 'fresh_milk_iced_tea', 'bubble_tea'],
    default_serving_option: 'hot_tea_latte'
  }
]

// Sample categories for organization
export const teaCategories = [
  {
    id: 'black-tea',
    name: 'Black Tea',
    description: 'Full-bodied teas with robust flavors, perfect for morning or afternoon',
    color: '#8B4513',
    image: '/images/categories/black-tea.jpg'
  },
  {
    id: 'green-tea',
    name: 'Green Tea',
    description: 'Light and refreshing teas with grassy, vegetal notes',
    color: '#228B22',
    image: '/images/categories/green-tea.jpg'
  },
  {
    id: 'white-tea',
    name: 'White Tea',
    description: 'Delicate and subtle teas with the least processing',
    color: '#F5F5DC',
    image: '/images/categories/white-tea.jpg'
  },
  {
    id: 'oolong-tea',
    name: 'Oolong Tea',
    description: 'Semi-oxidized teas with complex flavors between black and green',
    color: '#DAA520',
    image: '/images/categories/oolong-tea.jpg'
  },
  {
    id: 'herbal-tea',
    name: 'Herbal Tea',
    description: 'Caffeine-free infusions made from herbs, flowers, and fruits',
    color: '#9370DB',
    image: '/images/categories/herbal-tea.jpg'
  },
  {
    id: 'puerh-tea',
    name: 'Pu-erh Tea',
    description: 'Aged and fermented teas with deep, earthy flavors',
    color: '#8B0000',
    image: '/images/categories/puerh-tea.jpg'
  },
  {
    id: 'flavored-tea',
    name: 'Flavored Tea',
    description: 'Teas blended with spices, flowers, and natural flavors',
    color: '#FF6347',
    image: '/images/categories/flavored-tea.jpg'
  }
]

// Sample admin user for testing
export const sampleAdminUser = {
  uid: 'admin-user-123',
  email: 'admin@elecafe.ca',
  displayName: 'Ele Cafe Admin',
  role: 'admin',
  createdAt: new Date().toISOString()
}

// Sample orders for testing
export const sampleOrders = [
  {
    id: 'order-001',
    orderId: 'ELE-2025-001',
    customerId: 'customer-123',
    customerName: 'John Smith',
    customerEmail: 'john.smith@email.com',
    customerPhone: '+1-555-0123',
    status: 'pending',
    paymentStatus: 'pending',
    items: [
      {
        id: 'black-earl-grey',
        name: 'Earl Grey Supreme',
        price: 24.99,
        quantity: 2,
        category: 'Black Tea'
      },
      {
        id: 'green-matcha',
        name: 'Ceremonial Grade Matcha',
        price: 45.99,
        quantity: 1,
        category: 'Green Tea'
      }
    ],
    subtotal: 95.97,
    tax: 12.48,
    shipping: 0,
    total: 108.45,
    shippingAddress: {
      street: '123 Main Street',
      city: 'Toronto',
      province: 'ON',
      postalCode: 'M5V 3A8',
      country: 'Canada'
    },
    specialInstructions: 'Please include brewing instructions',
    notificationPreferences: {
      email: true,
      sms: true
    },
    createdAt: new Date().toISOString()
  }
]

export default {
  sampleTeaProducts,
  teaCategories,
  sampleAdminUser,
  sampleOrders,
  servingOptions
}

